### ISSUE TITLE
Stop working in new Vue 2.2.0

### ISSUE THREAD

**Issue by natocTo** [hilongjw/vue-lazyload#120]
Maybe you already notice. 

My app stop working after update Vue to newest version, with no specific error. But after comment out all v-lazy usage it was back working.

btw: No specific errors because it was production build, my mistake.

**Comment by jvandenaardweg** [comment]
```javascript
TypeError: e.util.isObject is not a function
    at a.value (vue-lazyload.js:6)
    at a.value (vue-lazyload.js:6)
    at callHook$1 (vue.runtime.common.js:5102)
    at _update (vue.runtime.common.js:5028)
    at Array.updateDirectives (vue.runtime.common.js:5009)
    at invokeCreateHooks (vue.runtime.common.js:4607)
    at createElm (vue.runtime.common.js:4501)
    at createChildren (vue.runtime.common.js:4591)
    at createElm (vue.runtime.common.js:4499)
    at createChildren (vue.runtime.common.js:4591)
logError @ vue.runtime.common.js:418
```

https://github.com/vuejs/vue/releases/tag/v2.2.0

I think it has to do with this change in vue 2.2.0:

> Many exposed methods and properties on Vue.util have been removed. If you previously relied on them, you should migrate off of them since this object is intended for internal use only - it is not (and has never been) considered part of the public API and may change without notice in the future.

**Comment by hilongjw** [comment]
i will fix it soon

**Comment by hilongjw** [comment]
fixed in [https://github.com/hilongjw/vue-lazyload/releases/tag/1.0.0-rc12]
